config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :planes, only: [:create, :show, :edit, :destroy]

  root :to => 'planes#index'

  namespace :api do
    namespace :v1 do
      resources :planes, only: [:index, :create, :destroy, :update] 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plane.rb
class Plane < ApplicationRecord
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController

  respond_to :json


end

app/controllers/api/v1/planes_controller.rb
class Api::V1::PlanesController < Api::V1::BaseController

  def index
    respond_with Plane.all
  end

  def create
    respond_with :api, :v1, Plane.create(plane_params)
  end

  def destroy
    respond_with Plane.destroy(params[:id])
  end

  def update
    plane = Plane.find(params[:id])
    plane.update_attributes(plane_params)
    respond_with plane, json: plane
  end

  private

  def plane_params
    params.require(:plane).permit(:model_id, :description, :datetime, :longitude, :latitude, :elevation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:id, :description, :datetime, :longitude, :latitude, :elevation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Texada</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planes/_form.html.erb
<%= form_for(plane) do |f| %>
  <% if plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :datetime %>
    <%= f.datetime_select :datetime %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :elevation %>
    <%= f.text_field :elevation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<%= react_component 'Main' %>

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Id:</strong>
  <%= @plane.id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plane.description %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @plane.datetime %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @plane.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @plane.latitude %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @plane.elevation %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>